spring:
  application:
    name: minidrive

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/minidrive}
    username: ${DB_USERNAME:minidrive}
    password: ${DB_PASSWORD:minidrive}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

server:
  port: 8080
