spring:
  application:
    name: minidrive

  datasource:
    url: jdbc:postgresql://localhost:5432/minidrive
    username: minidrive
    password: minidrive

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

server:
  port: 8080
